<main>
    <form method="post" action="index.php">
        <fieldset>
            <label for="email">Email</label>
            <input type="email" id="email" name="email" required />
        </fieldset>
        <fieldset>
            <label for="password">Mot de passe</label>
            <input type="password" id="password" name="password" required />
        </fieldset>
        <fieldset>
            <button type="submit">Connexion</button>
        </fieldset>
    </form>
</main>